name: Build Xiaomi Marble Kernel

on:
  workflow_dispatch:  # Manual trigger for the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Remove Useless Package
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
        sudo apt -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo apt -y autoremove --purge
        sudo apt -y autoclean
        sudo apt clean

    - name: Install Package For Build
      run: |
        sudo apt update && sudo apt install -y curl liblz4-1 libyaml-0-2 p7zip-full gcc g++ bison bc make git zip flex zipalign libssl-dev python3 gcc-aarch64-linux-gnu cpio

    - name: Maximize Build Space
      uses: easimon/maximize-build-space@master
      with:
        swap-size-mb: 30720
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'

    - name: Checkout kernel source
      run: |
        git clone https://github.com/Pzqqt/android_kernel_xiaomi_marble.git
        cd android_kernel_xiaomi_marble

    - name: Show Kernel Source File List
      run: |
        ls -l android_kernel_xiaomi_marble

    - name: Download and set up clang toolchain
      run: |
        mkdir -p /opt/clang
        wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/428d18d9732aa7ebfcaed87a582d86155db878d4/clang-r416183b.tar.gz
        tar -xzf clang-r416183b.tar.gz -C /opt/clang
        export PATH="/opt/clang/bin:$PATH"

    - name: Show Toolchain File List
      run: |
        ls -l /opt/clang

    - name: Clean and Build the kernel
      run: |
        cd android_kernel_xiaomi_marble
        make ARCH=arm64 LLVM=1 LLVM_IAS=1 O=out mrproper
        make ARCH=arm64 LLVM=1 LLVM_IAS=1 O=out marble_defconfig
        make ARCH=arm64 LLVM=1 LLVM_IAS=1 O=out -j$(nproc --all)
