name: get repo.prop mainfest.xml

on:
    push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Download Build Tools
      run: |
        cd $GITHUB_WORKSPACE
        git clone https://gerrit.googlesource.com/git-repo
        mkdir android-kernel && cd android-kernel
        ../git-repo/repo init --depth=1 --u https://android.googlesource.com/kernel/manifest -b common-android12-5.10
        ../git-repo/repo sync
        cd ../git-repo/
        ls

    - name: Debug - List Files
      run: |
        find $GITHUB_WORKSPACE/android-kernel -type f

    - name: Download repo.prop and manifest.xml
      run: |
        if [ -f $GITHUB_WORKSPACE/android-kernel/.repo/repo.prop ]; then
          cp $GITHUB_WORKSPACE/android-kernel/.repo/repo.prop $GITHUB_WORKSPACE/
        else
          echo "repo.prop not found"
        fi
        if [ -f $GITHUB_WORKSPACE/android-kernel/.repo/manifests/manifest.xml ]; then
          cp $GITHUB_WORKSPACE/android-kernel/.repo/manifests/manifest.xml $GITHUB_WORKSPACE/
        else
          echo "manifest.xml not found"
        fi

    - name: Upload repo.prop and manifest.xml
      uses: actions/upload-artifact@v3
      with:
        name: repo-files
        path: |
          ${{ github.workspace }}/repo.prop
          ${{ github.workspace }}/android-kernel/.repo/manifest.xml
