name: Get repo.prop

on: 
  push:

jobs:
  get-repo-prop:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Git and Repo
      run: |
        sudo apt-get update
        sudo apt-get install git
        python -m pip install --upgrade pip
        pip install repo

    - name: Initialize Repo
      run: |
        cd $GITHUB_WORKSPACE
        git clone https://gerrit.googlesource.com/git-repo
        mkdir android-kernel && cd android-kernel
        $GITHUB_WORKSPACE/git-repo/repo init --depth=1 --no-repo-verify --url https://android.googlesource.com/kernel/manifest -b common-android12-5.10

    - name: Sync Repo (minimal)
      run: |
        cd $GITHUB_WORKSPACE/android-kernel
        repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune

    - name: Upload repo.prop
      uses: actions/upload-artifact@v3
      with:
        name: repo-prop
        path: ${{ github.workspace }}/android-kernel/.repo/repo.prop
