name: Download Android Kernel Source

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        sudo apt update && sudo apt install -y git curl

    - name: Maximize Build Space
      uses: easimon/maximize-build-space@master
      with:
        swap-size-mb: 4096

    - name: Clone git-repo
      run: |
        cd $GITHUB_WORKSPACE
        git clone https://gerrit.googlesource.com/git-repo

    - name: Initialize and Sync Android Kernel Source
      run: |
        cd $GITHUB_WORKSPACE
        mkdir android-kernel && cd android-kernel
        ../git-repo/repo init --depth=1 --manifest-url https://android.googlesource.com/kernel/manifest --branch common-android12-5.10
        ../git-repo/repo sync

    - name: Package Kernel Source
      run: |
        # 假设内核源代码在 'kernel' 目录下
        cd $GITHUB_WORKSPACE/android-kernel
        zip -r kernel-source.zip ./*

    - name: Upload Kernel Source Package
      uses: actions/upload-artifact@v3
      with:
        name: android-kernel-source
        path: $GITHUB_WORKSPACE/android-kernel/kernel-source.zip
