name: Download Android Kernel Source

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        sudo apt update && sudo apt install -y git curl

    - name: Maximize Build Space
      uses: easimon/maximize-build-space@master
      with:
        swap-size-mb: 4096
        
    - name: Remove Existing git-repo Directory
      run: |
        # 检查 git-repo 目录是否存在，如果存在则删除
        if [ -d "$GITHUB_WORKSPACE/git-repo" ]; then
          rm -rf "$GITHUB_WORKSPACE/git-repo"
        fi

    - name: Initialize and Sync Android Kernel Source
      run: |
        cd $GITHUB_WORKSPACE
        git clone https://gerrit.googlesource.com/git-repo
        mkdir android-kernel && cd android-kernel
        cd mkdir test.txt
        
    - name: Package Kernel Source
      run: |
        cd $GITHUB_WORKSPACE/android-kernel
        zip -r kernel-source.zip ./*

    - name: Upload Kernel Source Package
      uses: actions/upload-artifact@v3
      with:
        name: android-kernel-source
        path: $GITHUB_WORKSPACE/android-kernel/kernel-source.zip
