name: Build android common kernel

on:
    push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Package For Build

      run: |
        sudo apt update && sudo apt install -y curl liblz4-1 libyaml-0-2 p7zip-full gcc g++ bison bc make git zip flex zipalign libssl-dev python3 gcc-aarch64-linux-gnu cpio
    - name: Maximize Build Space

      uses: easimon/maximize-build-space@master

      with:

        swap-size-mb: 20480

        remove-dotnet: 'true'

        remove-android: 'true'

        remove-haskell: 'true'

    - name: Checkout android-cuttlefish
      run: |
        git clone https://github.com/google/android-cuttlefish.git
        cd android-cuttlefish
        echo "repo cloned"

    - name: Install required build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git devscripts equivs config-package-dev debhelper-compat golang curl

    - name: Build .deb packages
      run: |
        cd android-cuttlefish
        tools/buildutils/build_packages.sh

    - name: Package source and .deb files
      run: |
        cd android-cuttlefish
        mkdir -p package
        cp *.deb package/  # 复制生成的 .deb 包
        tar -czvf cuttlefish_package.tar.gz -C package .

    - name: Upload source and .deb artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cuttlefish-source-and-debs
        path: cuttlefish_package.tar.gz
        
    - name: Download Build Tools

      run: |
        cd $GITHUB_WORKSPACE
        git clone https://gerrit.googlesource.com/git-repo
        mkdir android-kernel && cd android-kernel
        ../git-repo/repo init --depth=1 -u https://android.googlesource.com/kernel/manifest -b common-android12-5.10 --depth 1
        ../git-repo/repo sync
        ls -l
    - name: Build Kernel
      run: |
        cd $GITHUB_WORKSPACE/android-kernel
        LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh
        bash build/build.sh
